test_task/input_output/urls.py
from django.urls import path, include
from .views import IndexView, InputView, OutputView

app_name = 'input_output'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('input/', InputView.as_view(), name='input'),
    path('output/', OutputView.as_view(), name='output'),
]

test_task/test_task/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('input_output.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

test_task/input_output/models.py
from django.db import models
from django.contrib.postgres.fields.jsonb import JSONField


class SomeData(models.Model):
    data = JSONField()

test_task/input_output/forms.py
from django import forms


class InputForm(forms.Form):
    name = forms.CharField(max_length=200)
    msg  = forms.CharField(max_length=2000)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

test_task/input_output/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from .models import SomeData
from .forms import InputForm


class IndexView(TemplateView):
    template_name = 'input_output/index.html'

class InputView(TemplateView):
    template_name = 'input_output/input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = InputForm()
        return context

    def post(self, *args, **kwargs):
        names    = self.request.POST.getlist('name')
        messages = self.request.POST.getlist('msg')

        for name, msg in zip(names, messages):
            SomeData.objects.create(data={
                'name': name,
                'msg': msg,
            })

        context =  self.get_context_data()
        context['success'] = True

        return render(self.request, self.template_name, context)

class OutputView(TemplateView):
    template_name = 'input_output/output.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.method == 'GET':
            context['data'] = SomeData.objects.all()

        return context

test_task/input_output/templates/input_output/forms/empty_form.html
<div class="row">
    <div class="col-11 my-2">
        <div class="row">
            <div class="col-6">{{ form.name }}</div>
            <div class="col-6">{{ form.msg }}</div>
        </div>
    </div>
    <div class="col-1 my-2">
        <button type="button" class="close remove-form" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
<script>
    $(".remove-form").click(function() {
        $(this).parent().parent().html("")
    })
</script>

test_task/input_output/templates/input_output/index.html
{% extends 'base.html' %}
{% block title %}InputOutputApp | Main page{% endblock %}
{% block content %}
<div class="container">
    <hr>
    <a href="{% url 'input_output:input' %}">Go to input page!</a>
    <hr>
    <a href="{% url 'input_output:output' %}">Go to output page!</a>
    <hr>
</div>
{% endblock %}

test_task/input_output/templates/input_output/input.html
{% extends 'base.html' %}
{% block title %}InputOutputApp | Input page{% endblock %}
{% block content %}
{% if success %}
<div class="alert alert-warning alert-dismissible fade show container" role="alert">
    <strong>Data published successfully!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div> 
{% endif %}
{{ input_formset.management_form }}
<form method="POST">
    {% csrf_token %}
    <div class="container">
        <div id="input-stack" class="">
            {% include 'input_output/forms/empty_form.html' with form=form %}
        </div>
        <hr>
        <button id="add-input-btn" class="btn btn-secondary btn-block">Add another input</button>
        <button type="submit" class="btn btn-info btn-block">Publish data</button>
        <hr>
        <a href="{% url 'input_output:output' %}">Go to output page!</a>
    </div>
</form>
<div id="empty-form" style="display: none;">
    {% include 'input_output/forms/empty_form.html' with form=form %}
</div>
<script>
    $("#add-input-btn").click(function() {
        new_input_form = $("#empty-form").html()
        $("#input-stack").append(new_input_form)
    })
</script>
{% endblock %}

test_task/input_output/templates/input_output/output.html
{% extends 'base.html' %}
{% block title %}InputOutputApp | Output page{% endblock %}
{% block content %}
<div class="container">
    {% for obj in data %}
        {{ obj.data }}
    {% endfor %}
    <hr>
    <a href="{% url 'input_output:input' %}">Go to input page!</a>
</div>
{% endblock %}

test_task/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>